export const medicalSpecialties = [
  { id: "general_practice", ar: "الطب العام", fr: "Médecine générale" },
  { id: "pediatrics", ar: "طب الأطفال", fr: "Pédiatrie" },
  { id: "cardiology", ar: "أمراض القلب", fr: "Cardiologie" },
  { id: "dermatology", ar: "الأمراض الجلدية", fr: "Dermatologie" },
  { id: "gynecology", ar: "أمراض النساء والتوليد", fr: "Gynécologie-obstétrique" },
  { id: "ophthalmology", ar: "طب العيون", fr: "Ophtalmologie" },
  { id: "orthopedics", ar: "جراحة العظام", fr: "Orthopédie" },
  { id: "neurology", ar: "طب الأعصاب", fr: "Neurologie" },
  { id: "psychiatry", ar: "الطب النفسي", fr: "Psychiatrie" },
  { id: "dentistry", ar: "طب الأسنان", fr: "Dentisterie" },
  { id: "ent", ar: "طب الأنف والأذن والحنجرة", fr: "O.R.L" },
  { id: "internal_medicine", ar: "الطب الباطني", fr: "Médecine interne" },
  { id: "gastroenterology", ar: "أمراض الجهاز الهضمي", fr: "Gastro-entérologie" },
  { id: "endocrinology", ar: "الغدد الصماء والسكري", fr: "Endocrinologie et diabétologie" },
  { id: "urology", ar: "جراحة المسالك البولية", fr: "Urologie" },
  { id: "pulmonology", ar: "الأمراض الصدرية", fr: "Pneumologie" },
  { id: "rheumatology", ar: "أمراض المفاصل والروماتيزم", fr: "Rhumatologie" },
  { id: "nephrology", ar: "أمراض الكلى", fr: "Néphrologie" },
  { id: "oncology", ar: "طب الأورام", fr: "Oncologie" },
  { id: "hematology", ar: "أمراض الدم", fr: "Hématologie" },
  { id: "infectious_diseases", ar: "الأمراض المعدية", fr: "Maladies infectieuses" },
  { id: "general_surgery", ar: "الجراحة العامة", fr: "Chirurgie générale" },
  { id: "pediatric_surgery", ar: "جراحة الأطفال", fr: "Chirurgie pédiatrique" },
  { id: "neurosurgery", ar: "جراحة المخ والأعصاب", fr: "Neurochirurgie" },
  { id: "plastic_surgery", ar: "الجراحة التجميلية", fr: "Chirurgie plastique" },
  { id: "radiology", ar: "الأشعة", fr: "Radiologie" },
  { id: "anesthesiology", ar: "التخدير والإنعاش", fr: "Anesthésiologie et réanimation" },
  { id: "physical_therapy", ar: "الطب الفيزيائي وإعادة التأهيل", fr: "Médecine physique et réadaptation" },
  { id: "sports_medicine", ar: "الطب الرياضي", fr: "Médecine du sport" },
  { id: "nutrition", ar: "التغذية", fr: "Nutrition" },
  { id: "allergy_immunology", ar: "الحساسية والمناعة", fr: "Allergologie et immunologie" },
  { id: "medical_laser", ar: "ليزر طبي بدون جراحة", fr: "Laser médical sans chirurgie" }
];
